### ISSUE TITLE
New Discord update broke the script

### ISSUE THREAD

**Issue by EngineExt** [An00nymushun/DiscordFreeStickers#35]
**Describe the bug**
New Discord update broke the script

**To Reproduce**
Update discord

- Update discord
- Enable plugin

**Expected behavior**
Script starting and working

**log**
```
c83be22….js:1 [PluginManager] FreeStickers v1.4.0 could not be started.

 Error: Couldn't find StickerSendabilityModule
    at Object.Start [as start] (FreeStickers.plugin.js:3754:11)
    at A.startPlugin (renderer.js:5:35363)
    at A.startAddon (renderer.js:5:35156)
    at A.enableAddon (renderer.js:5:8634)
    at A.toggleAddon (renderer.js:5:8891)
    at A.togglePlugin (renderer.js:5:32444)
    at renderer.js:5:87082
    at renderer.js:5:79852
    at Object.eN (a2b67f3….js:1:751257)
    at eB (a2b67f3….js:1:751411)
```

**Client:**

- Desktop [Windows 10 64-Bit (10.0.19045)]
- Discord Build Channel [Stable 245648 (758ffd2)]
- Plugin Version [1.4.0]
- BD Version [1.9.6]

**Comment by FerLuisxd** [comment]
Hopefully the dev sees this, he hasn't made a commit to the repo in about a year :(. 
Otherwhise might be better to look into other options? I really don't know any tbh

**Comment by J-Stuff** [comment]
https://github.com/riolubruh/DiscordFreeStickers is a more up-to-date fork of this repo. However the developer hasn't made a patch to fix the latest update either.

(Edit: is up-to-date now!)
